EFFIS_CONTINUE  = "EFFIS_CONTINUE"
EFFIS_SIGTERM   = "EFFIS_SIGTERM"
EFFIS_SIGKILL   = "EFFIS_SIGKILL"
EFFIS_QUIT      = "EFFIS_QUIT"

EFFIS_HEARTBEAT_NOT_DETECTED \
                = "EFFIS_HEARTBEAT_NOT_DETECTED"

CLIENT_READY    = "CLIENT_READY"
CLIENT_DONE     = "CLIENT_DONE"
