EFFIS_CONTINUE  = "EFFIS_CONTINUE"
EFFIS_SIGTERM   = "EFFIS_SIGTERM"
EFFIS_SIGKILL   = "EFFIS_SIGKILL"
EFFIS_HEARTBEAT = "EFFIS_HEARTBEAT"

CLIENT_READY    = "CLIENT_READY"
CLIENT_DONE     = "CLIENT_DONE"
